Revert "configure: Check for make"
This reverts commit 89025585cde1e2696c134b3cb7457abd6a3c3933.

This check breaks BSD builds and isn't useful through the configure
process. The README describes the build environment requirements (GNU
make).

Change-Id: I25f8a9c1640909412ab405dbd09a1c4d93e5a511

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -161,11 +161,9 @@ for t in ${all_targets}; do
     [ -f ${source_path}/${t}.mk ] && enable_feature ${t}
 done
 
-for util in make perl; do
-    if ! ${util} --version >/dev/null; then
-        die "${util} is required to build."
-    fi
-done
+if ! perl --version >/dev/null; then
+    die "Perl is required to build"
+fi
 
 
 if [ "`cd ${source_path} && pwd`" != "`pwd`" ]; then
