configure: check for perl
Though not (currently) required this tests for perl in all
configurations.

Fixes issue #671

Change-Id: Ibe1e72db74bb4cf3252b73c68ff1dfc2ecfc902b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -160,6 +160,10 @@ for t in ${all_targets}; do
     [ -f ${source_path}/${t}.mk ] && enable_feature ${t}
 done
 
+if ! perl --version >/dev/null; then
+    die "Perl is required to build"
+fi
+
 # check installed doxygen version
 doxy_version=$(doxygen --version 2>/dev/null)
 doxy_major=${doxy_version%%.*}
